### ISSUE TITLE
Ticket #3 - Mettez en place une stratégie de tests (par le Tech Lead)

### ISSUE THREAD

**Issue by franckblack** [NlCO/BibliOC#5]
Après un code review de la V1 je me suis rendu compte que des tests unitaires n’ont pas été implémentés, on est donc hors des process de qualité sur cette release....

Pour la release qui est en cours de développement, merci de mettre en place une stratégie de tests pour le code API :

Des tests unitaires pour valider les parties métiers du code API (l’utilisation de JUnit devrait faire l’affaire, à vous de voir s’il y a besoin de faire des mocks ou non) 
Des tests d’intégration de l’API via un outil de tests d’API (ex : Postman, Soap-UI)
Pour les tests de l’application web et du batch, on verra dans un second temps. Je vous tiendrai au courant…

**Comment by NlCO** [comment]
TU : OK
TI : via Cucumber + Jeu de test Postman : OK

**Comment by franckblack** [comment]
j'ai vu cela niquel


Cordialement


Didier Stéphane

Téléphone : 06.43.07.62.72
Contact : contact@helios-multimedia.fr<mailto:contact@helios-multimedia.fr>
Site Internet : http://www.helios-multimedia.fr<http://www.helios-multimedia.com>

________________________________
De : NlCO <notifications@github.com>
Envoyé : lundi 8 juin 2020 21:41
À : NlCO/BibliOC <BibliOC@noreply.github.com>
Cc : franckblack <stephane.didier@live.fr>; Author <author@noreply.github.com>
Objet : Re: [NlCO/BibliOC] Ticket #3 - Mettez en place une stratégie de tests (par le Tech Lead) (#5)


TU : OK
TI : via Cucumber + Jeu de test Postman : OK

**Comment by NlCO** [comment]
Livré sur master
